[installer-tests] disable npm version update notice
This is a small quality of life improvement for the self hosted terraform tests.

Unnecessary log chatter is a source of distraction while debugging failed CI jobs. While looking at werft failures npx emits the following message:

[gitpod-custom-alt-stream-exec-logs.2](https://werft.gitpod-dev.com/job/gitpod-custom-alt-stream-exec-logs.2)

```
Could not find license, skipping replicated license cleanup
FailedSliceError: create-gcp-infra
    at new FailedSliceError (/workspace/.werft/util/werft.ts:8:9)
    at Werft.fail (/workspace/.werft/util/werft.ts:117:15)
    at /workspace/.werft/installer-tests.ts:291:19
    at step (/workspace/.werft/installer-tests.ts:33:23)
    at Object.next (/workspace/.werft/installer-tests.ts:14:53)
    at fulfilled (/workspace/.werft/installer-tests.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm notice
npm notice New minor version of npm available! 8.11.0 -> 8.19.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.2>
npm notice Run `npm install -g npm@8.19.2` to update!
npm notice
```

There will almost certainly never be a time where we'll upgrade npm solely because of a message sent to stderr in a CI job; it doesn't provide any value for us and will chew up more mental cycles than necessary. This commit disables npm update notifications within our CI jobs.