[.github] prometheus-redis-exporter:latest is no longer available (#20450)
* [.github] prometheus-redis-exporter:latest is no longer available

We get:
crane digest cgr.dev/chainguard/prometheus-redis-exporter:latest
2024/12/13 21:09:14 HEAD request failed, falling back on GET: HEAD https://cgr.dev/v2/chainguard/prometheus-redis-exporter/manifests/latest: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)
Error: GET https://cgr.dev/v2/chainguard/prometheus-redis-exporter/manifests/latest: MANIFEST_UNKNOWN: Unknown manifest

I'm disabling both for now, so that we can update other images.

* update index (#20449)

Co-authored-by: kylos101 <kylos101@users.noreply.github.com>

* Revert "update index (#20449)"

This reverts commit 74c4977810ea28aa3427c535ff18b7c3bf3fbd1b.

---------

Co-authored-by: Robo Quat <87151047+roboquat@users.noreply.github.com>
Co-authored-by: kylos101 <kylos101@users.noreply.github.com>