[test] fix TestOpenWorkspaceFromOutdatedPrebuild
Because of:
--- FAIL: TestOpenWorkspaceFromOutdatedPrebuild (26.72s)
    --- FAIL: TestOpenWorkspaceFromOutdatedPrebuild/prebuild (26.72s)
        --- FAIL: TestOpenWorkspaceFromOutdatedPrebuild/prebuild/it_should_open_a_workspace_from_with_an_older_prebuild_initializer_successfully_and_run_the_init_task (26.72s)
            --- FAIL: TestOpenWorkspaceFromOutdatedPrebuild/prebuild/it_should_open_a_workspace_from_with_an_older_prebuild_initializer_successfully_and_run_the_init_task/classic (26.72s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x259345e]