[test] update convenience script to manually run tests & remove werft test scripts/references (#17854)
* Fix run.sh to use go-junit-report, and avoid werft mostly, except for secrets

* View results with xunit-viewer

* Remove werft integration test script/automation

* Exclude test output

* Create results folder if doesn't exit

* Empty

* [test] match the github action workflow `go test` params

* [test] install xunit-viewer once & clean-up rogue ports at the end

* [test] fix TestOpenWorkspaceFromOutdatedPrebuild

Because of:
--- FAIL: TestOpenWorkspaceFromOutdatedPrebuild (26.72s)
    --- FAIL: TestOpenWorkspaceFromOutdatedPrebuild/prebuild (26.72s)
        --- FAIL: TestOpenWorkspaceFromOutdatedPrebuild/prebuild/it_should_open_a_workspace_from_with_an_older_prebuild_initializer_successfully_and_run_the_init_task (26.72s)
            --- FAIL: TestOpenWorkspaceFromOutdatedPrebuild/prebuild/it_should_open_a_workspace_from_with_an_older_prebuild_initializer_successfully_and_run_the_init_task/classic (26.72s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x259345e]

* Use absolute results dir

* Make results dir per run

---------

Co-authored-by: WVerlaek <wouter@gitpod.io>